"""Initial database schema

Revision ID: 0efde3d95075
Revises: 
Create Date: 2025-10-24 12:34:07.333859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efde3d95075'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user')", name='users_role_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('current_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('error_info_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('PROCESSING', 'CANCELLING', 'SUCCESS', 'FAILURE')", name='current_tasks_status_check'),
    sa.CheckConstraint('completed_items >= 0', name='current_tasks_completed_items_check'),
    sa.CheckConstraint('total_items >= 0', name='current_tasks_total_items_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_tasks_status'), 'current_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_current_tasks_user_id'), 'current_tasks', ['user_id'], unique=True)
    op.create_table('salon_board_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('setting_name', sa.String(length=100), nullable=False),
    sa.Column('sb_user_id', sa.String(length=255), nullable=False),
    sa.Column('encrypted_sb_password', sa.String(length=512), nullable=False),
    sa.Column('salon_id', sa.String(length=100), nullable=True),
    sa.Column('salon_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salon_board_settings_id'), 'salon_board_settings', ['id'], unique=False)
    op.create_index(op.f('ix_salon_board_settings_user_id'), 'salon_board_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salon_board_settings_user_id'), table_name='salon_board_settings')
    op.drop_index(op.f('ix_salon_board_settings_id'), table_name='salon_board_settings')
    op.drop_table('salon_board_settings')
    op.drop_index(op.f('ix_current_tasks_user_id'), table_name='current_tasks')
    op.drop_index(op.f('ix_current_tasks_status'), table_name='current_tasks')
    op.drop_table('current_tasks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
